apiVersion: apps/v1
kind: Deployment
metadata:
  name: efp-graphql-gateway
  namespace: efp-production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: efp-graphql-gateway
  template:
    metadata:
      labels:
        app: efp-graphql-gateway
    spec:
      containers:
        - name: gql
          image: node:20-alpine
          command: ["node", "src/server.js"]
          workingDir: /app
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: app-src
              mountPath: /app
      volumes:
        - name: app-src
          hostPath:
            path: /opt/efp/graphql-gateway
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: efp-graphql-gateway
  namespace: efp-production
spec:
  selector:
    app: efp-graphql-gateway
  ports:
    - port: 4000
      targetPort: 4000