apiVersion: v1
kind: Service
metadata:
  name: efp-api-gateway
  namespace: efp-production
spec:
  selector:
    app: efp-api-gateway
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP