apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: communication-service
  namespace: efp-production
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: communication.efp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: communication-service
                port:
                  number: 3001
  tls:
    - hosts:
        - communication.efp.local
      secretName: communication-service-tls